In [3]:
import time
from datetime import datetime, date, timedelta
from sqlalchemy import create_engine
import pandas as pd

In [4]:
# nimbus_db_connection = 'mysql+pymysql://tableau_nimbus:LNcNqdk9Tqk3v6@nimbus-slave-tableau.clwjnp7sjnpx.ap-south-1.rds.amazonaws.com/shipping'
# nimbus_db = create_engine(nimbus_db_connection)

In [5]:
si_db_connection = 'mysql+pymysql://admin:Qazwsx123@sourceinfi-read-replica.clwjnp7sjnpx.ap-south-1.rds.amazonaws.com/voehoo' 
si_db = create_engine(si_db_connection)

In [99]:
start_date= str(date.today()- timedelta(1))  
end_date= str( date.today() )
print(start_date,'    ',end_date)  

fromDate=int(time.mktime((datetime.strptime(start_date,"%Y-%m-%d")).timetuple()))
toDate=int(time.mktime((datetime.strptime(end_date,"%Y-%m-%d")).timetuple())) 
print(fromDate,'    ',toDate)

2023-12-05      2023-12-06
1701714600      1701801000

In [44]:
# a=datetime.now()
# sql='select * from users;'
# users=pd.read_sql(sql, con=si_db) 
# print(datetime.now()-a)
# users

In [100]:
a=datetime.now()

# sql='SELECT s.vendor_id as Vendor_ID, uv.company_name as Vendor_Name, s.seller_id as Seller_ID, us.company_name as Seller_Name, s.awb_number as AWB, pv.si_sku as SKU, sot.product_name as Product_name, DATE_FORMAT(from_unixtime(so.order_date),"%%Y-%%m-%%d") as Order_Date, DATE_FORMAT(from_unixtime(s.created),"%%Y-%%m-%%d") as Shipment_Date, DATE_FORMAT(from_unixtime(s.pickup_time),"%%Y-%%m-%%d") as Pickup_Time, DATE_FORMAT(from_unixtime(sot.approved_time),"%%Y-%%m-%%d") as Approved_Time, s.ship_status as Ship_Status FROM shippings AS s LEFT JOIN shopify_order_items AS sot ON s.order_item_id = sot.id LEFT JOIN shopify_orders AS so ON sot.order_id = so.id LEFT JOIN product_variants AS pv ON pv.si_sku = sot.variant_sku LEFT JOIN users AS uv ON uv.id= s.vendor_id LEFT JOIN users AS us ON us.id= s.seller_id WHERE so.order_date >= '+str(fromDate)+' AND so.order_date < '+str(toDate)+' AND s.ship_status NOT IN ("cancelled"); '

# sql='''
#     SELECT
#     s.vendor_id as Vendor_ID, uv.company_name as Vendor_Name, 
#     s.seller_id as Seller_ID, us.company_name as Seller_Name, 
#     s.awb_number as AWB, pv.si_sku as SKU, sot.product_name as Product_name, 
#     DATE_FORMAT(from_unixtime(so.order_date),"%%Y-%%m-%%d") as Order_Date, 
#     DATE_FORMAT(from_unixtime(s.created),"%%Y-%%m-%%d") as Shipment_Date, 
#     DATE_FORMAT(from_unixtime(s.pickup_time),"%%Y-%%m-%%d") as Pickup_Time, 
#     DATE_FORMAT(from_unixtime(sot.approved_time),"%%Y-%%m-%%d") as Approved_Time, 
#     s.ship_status as Ship_Status 

#     FROM shippings AS s 
#     LEFT JOIN shopify_order_items AS sot ON s.order_item_id = sot.id 
#     LEFT JOIN shopify_orders AS so ON sot.order_id = so.id 
#     LEFT JOIN product_variants AS pv ON pv.si_sku = sot.variant_sku 
#     LEFT JOIN products AS p ON p.id = pv.product_id 
#     LEFT JOIN users AS uv ON uv.id= s.vendor_id 
#     LEFT JOIN users AS us ON us.id= s.seller_id 
#     WHERE so.order_date >= '1699209000' AND so.order_date < '1701801000' 
#     AND s.ship_status NOT IN ("cancelled");
#     '''

df=pd.read_sql(sql, con=si_db) 
print(datetime.now()-a)
df

0:00:01.881489

,Vendor_ID,Vendor_Name,Seller_ID,Seller_Name,AWB,SKU,Product_name,Order_Date,Shipment_Date,Pickup_Time,Approved_Time,Ship_Status
0,3409,Lazy Window LLP,3368,A.D.Enterprise,STOC9000585535,SI30468,Magical High Pressure Washing & Cleaning Spray...,2023-12-05,2023-12-05,2023-12-05,2023-12-05,in transit
1,3132,Radha krishna handloom,3416,Store Bolt,SHBC7000129624,SI36190,WINTER ELASTIC PREMIUM BEDSHEET - Royal Blue,2023-12-05,2023-12-05,2023-12-05,2023-12-05,pending pickup
2,3108,Vivek g enterprises,3403,Rohit Gr,STOC9000588721,SI27758,Camera Body with 18-140 mm Lens,2023-12-05,2023-12-05,2023-12-05,2023-12-05,in transit
3,3108,Vivek g enterprises,3403,Rohit Gr,STOC9000597532,SI27758,Camera Body with 18-140 mm Lens,2023-12-05,2023-12-06,2023-12-06,2023-12-05,pending pickup
4,3107,RS Traders,3612,Bholenath Enterprises,14227882959034,SI36340,Love Couple Bracelet,2023-12-05,2023-12-05,2023-12-05,2023-12-05,in transit
...,...,...,...,...,...,...,...,...,...,...,...,...
7673,3409,Lazy Window LLP,3368,A.D.Enterprise,STOC9000597635,SI30455,Heavy Duty Garden Hose Nozzle Water Spray Gun ...,2023-12-05,2023-12-06,2023-12-06,2023-12-05,pending pickup
7674,3565,Meet fashion,3323,Khemka GOC,SHBC7000132616,SI35847,Imported Shoe Rack- High Quality,2023-12-05,2023-12-06,2023-12-06,2023-12-06,pending pickup
7675,3107,RS Traders,3157,aurum media works (New),STOC9000596734,SI27953,ReppaMart™ Adjustable Fit Cargo Pants - S / Kh...,2023-12-05,2023-12-06,2023-12-06,2023-12-06,pending pickup
7676,3565,Meet fashion,3323,Khemka GOC,SHBC7000132234,SI35847,Imported Shoe Rack- High Quality,2023-12-05,2023-12-06,2023-12-06,2023-12-06,pending pickup
7677,3409,Lazy Window LLP,3368,A.D.Enterprise,STOC9000593526,SI30468,Magical High Pressure Washing & Cleaning Spray...,2023-12-05,2023-12-06,2023-12-06,2023-12-05,pending pickup

In [102]:
df['Diff_Pickup_vs_Approval']=(pd.to_datetime(df.Pickup_Time).dt.date-pd.to_datetime(df.Approved_Time).dt.date).dt.days
df['Ship_Month']=pd.to_datetime(df.Shipment_Date).dt.strftime('%Y-%b')
df

,Vendor_ID,Vendor_Name,Seller_ID,Seller_Name,AWB,SKU,Product_name,Order_Date,Shipment_Date,Pickup_Time,Approved_Time,Ship_Status,Diff_Pickup_vs_Approval,Ship_Month
0,3409,Lazy Window LLP,3368,A.D.Enterprise,STOC9000585535,SI30468,Magical High Pressure Washing & Cleaning Spray...,2023-12-05,2023-12-05,2023-12-05,2023-12-05,in transit,0.0,2023-Dec
1,3132,Radha krishna handloom,3416,Store Bolt,SHBC7000129624,SI36190,WINTER ELASTIC PREMIUM BEDSHEET - Royal Blue,2023-12-05,2023-12-05,2023-12-05,2023-12-05,pending pickup,0.0,2023-Dec
2,3108,Vivek g enterprises,3403,Rohit Gr,STOC9000588721,SI27758,Camera Body with 18-140 mm Lens,2023-12-05,2023-12-05,2023-12-05,2023-12-05,in transit,0.0,2023-Dec
3,3108,Vivek g enterprises,3403,Rohit Gr,STOC9000597532,SI27758,Camera Body with 18-140 mm Lens,2023-12-05,2023-12-06,2023-12-06,2023-12-05,pending pickup,1.0,2023-Dec
4,3107,RS Traders,3612,Bholenath Enterprises,14227882959034,SI36340,Love Couple Bracelet,2023-12-05,2023-12-05,2023-12-05,2023-12-05,in transit,0.0,2023-Dec
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7673,3409,Lazy Window LLP,3368,A.D.Enterprise,STOC9000597635,SI30455,Heavy Duty Garden Hose Nozzle Water Spray Gun ...,2023-12-05,2023-12-06,2023-12-06,2023-12-05,pending pickup,1.0,2023-Dec
7674,3565,Meet fashion,3323,Khemka GOC,SHBC7000132616,SI35847,Imported Shoe Rack- High Quality,2023-12-05,2023-12-06,2023-12-06,2023-12-06,pending pickup,0.0,2023-Dec
7675,3107,RS Traders,3157,aurum media works (New),STOC9000596734,SI27953,ReppaMart™ Adjustable Fit Cargo Pants - S / Kh...,2023-12-05,2023-12-06,2023-12-06,2023-12-06,pending pickup,0.0,2023-Dec
7676,3565,Meet fashion,3323,Khemka GOC,SHBC7000132234,SI35847,Imported Shoe Rack- High Quality,2023-12-05,2023-12-06,2023-12-06,2023-12-06,pending pickup,0.0,2023-Dec
7677,3409,Lazy Window LLP,3368,A.D.Enterprise,STOC9000593526,SI30468,Magical High Pressure Washing & Cleaning Spray...,2023-12-05,2023-12-06,2023-12-06,2023-12-05,pending pickup,1.0,2023-Dec

In [107]:
pick_vs_approval=df.pivot_table(index='Diff_Pickup_vs_Approval', values='AWB', aggfunc='count', margins=True, 
                                margins_name='Grand_Total').reset_index().rename(columns={'AWB':'Shipments'})
# pick_vs_approval.rename(columns={'AWB':'Shipments'}, inplace=True)
pick_vs_approval['Ship_%']=((pick_vs_approval['Shipments']/pick_vs_approval['Shipments'].sum())*200).astype(int).astype(str)+'%'
pick_vs_approval

  Diff_Pickup_vs_Approval  Shipments Ship_%
0                     0.0       5845    76%
1                     1.0       1815    23%
2             Grand_Total       7660   100%

In [94]:
datewise_seller_status=df.pivot_table(index='Seller_Name', columns=['Ship_Month','Shipment_Date'], values='AWB', aggfunc='count', fill_value=0, 
                                      margins=True, margins_name='Grand_Total').reset_index().sort_values(by='Grand_Total', ascending=False)
datewise_seller_status

Ship_Month            Seller_Name   2023-Dec                                   \
Shipment_Date                     2023-12-01 2023-12-02 2023-12-03 2023-12-04
64                    Grand_Total       8088       8725       3832      16508
19             INTELLIQUESTGLOBAL        783       1129          1        757
50                            XYZ         89       1045          0        872
38                     Store Bolt        314        341          0        354
1                  A.D.Enterprise        446        469        445        499
..                            ...        ...        ...        ...        ...
62                   starviewzone          0          0          0          0
8                       ChillnBuy          0          0          0          0
14                   Ecom Sellers          0          0          0          0
3                 Alex John Group          0          0          0          0
18                 House Of Combo          0          0          0          0

Ship_Month                            2023-Nov                        ...  \
Shipment_Date 2023-12-05 2023-12-06 2023-11-06 2023-11-07 2023-11-08  ...
64                 11916       6418       3422      10110       7082  ...
19                  1250          0       1949       2585        250  ...
50                  1066        370          0          0          0  ...
38                   480        268        291        791       1407  ...
1                    615        857        291        478        751  ...
..                   ...        ...        ...        ...        ...  ...
62                     0          0          4          0          0  ...
8                      0          0          0          0          0  ...
14                     0          0          0          0          0  ...
3                      0          0          1          0          0  ...
18                     0          1          0          0          0  ...

Ship_Month                                                            \
Shipment_Date 2023-11-22 2023-11-23 2023-11-24 2023-11-25 2023-11-26
64                  8137       6115      12883      10150       6630
19                   150       2132        644       1942          5
50                  2040        474       3815       1819       1692
38                  1346        176       3265       1657         44
1                    508        398        641        293        481
..                   ...        ...        ...        ...        ...
62                     0          0          0          0          0
8                      1          0          0          0          0
14                     0          0          0          0          0
3                      0          0          0          0          0
18                     0          0          0          0          0

Ship_Month                                                Grand_Total
Shipment_Date 2023-11-27 2023-11-28 2023-11-29 2023-11-30
64                 12981      16745       9029      12753      257264
19                  3102       3087       1243       1606       37302
50                  3670       2628        876        852       27354
38                   349        173        143        525       26109
1                    605        548        343        497       18662
..                   ...        ...        ...        ...         ...
62                     0          0          0          0           4
8                      1          0          1          0           3
14                     0          1          0          1           2
3                      0          0          0          0           1
18                     0          0          0          0           1

[65 rows x 33 columns]

In [97]:
datewise_vendor_status=df.pivot_table(index='Vendor_Name', columns=['Ship_Month','Shipment_Date'], values='AWB', aggfunc='count', fill_value=0, 
                                      margins=True, margins_name='Grand_Total').reset_index().sort_values(by='Grand_Total', ascending=False)
datewise_vendor_status

Ship_Month                        Vendor_Name   2023-Dec             \
Shipment_Date                                 2023-12-01 2023-12-02
60                                Grand_Total       8088       8725
22                            Lazy Window LLP       2773       3004
18                            KATYANI TRADERS        428          0
38                                 RS Traders        542        347
41                           SS INTERNATIONAL        114       1989
..                                        ...        ...        ...
40                            SHIV ENTERPRISE          0          0
47                                SneakerZone          0          0
49                           Taparia Textiles          0          0
24                        M. KHODIYAR FASHION          0          0
17             Jai Shri Shani Dev Enterprises          0          0

Ship_Month                                                  2023-Nov  \
Shipment_Date 2023-12-03 2023-12-04 2023-12-05 2023-12-06 2023-11-06
60                  3832      16508      11916       6418       3422
22                  1952       3903       2617       1020       2327
18                     0       2937       1049        420        414
38                     0       1670       1470        548         36
41                   891        572        553        286          4
..                   ...        ...        ...        ...        ...
40                     0          0          0          0          0
47                     0          0          0          3          0
49                     0          0          0          0          0
24                     0          0          0          0          0
17                     0          0          0          0          0

Ship_Month                           ...                                   \
Shipment_Date 2023-11-07 2023-11-08  ... 2023-11-22 2023-11-23 2023-11-24
60                 10110       7082  ...       8137       6115      12883
22                  3527       4048  ...        667        595       2646
18                  1704        633  ...        386        448        544
38                   457        387  ...        926        301        359
41                     0          0  ...       1868        349       4017
..                   ...        ...  ...        ...        ...        ...
40                     0          0  ...          0          0          0
47                     0          0  ...          0          0          0
49                     0          0  ...          0          0          0
24                     0          0  ...          0          0          0
17                     0          0  ...          0          0          0

Ship_Month                                                            \
Shipment_Date 2023-11-25 2023-11-26 2023-11-27 2023-11-28 2023-11-29
60                 10150       6630      12981      16745       9029
22                  3178       1647       2879       5880        902
18                  1535          0        566       3580        376
38                   582        647       2199       2390       1175
41                   104        623        437        303        463
..                   ...        ...        ...        ...        ...
40                     0          0          0          0          0
47                     0          0          0          0          0
49                     0          0          0          0          0
24                     0          0          0          0          0
17                     0          0          1          0          0

Ship_Month               Grand_Total
Shipment_Date 2023-11-30
60                 12753      257264
22                  3639       85096
18                   378       24674
38                  1418       20509
41                   738       17261
..                   ...         ...
40                     0           4
47                     0           3
49                     0           1
24                     0           1
17                     0           1

[61 rows x 33 columns]

In [98]:
datewise_product_status=df.pivot_table(index='Product_name', columns=['Ship_Month','Shipment_Date'], values='AWB', aggfunc='count', fill_value=0, 
                                      margins=True, margins_name='Grand_Total').reset_index().sort_values(by='Grand_Total', ascending=False)
datewise_product_status

Ship_Month                                          Product_name   2023-Dec  \
Shipment_Date                                                    2023-12-01
1119                                                 Grand_Total       8088
495                                           Imported Shoe Rack        783
491                                           IMPORTED SHOE RACK        750
554            Magical High Pressure Washing & Cleaning Spray...        445
749            Rechargeable Torch Flashlight Long Distance Be...          0
...                                                          ...        ...
528            Lip Shape Apple Design Waterproof Lipstick Mat...          0
527            Lip Shape Apple Design Waterproof Lipstick Mat...          0
524                                                  Lip Plumper          0
523                                                 Lint Remover          0
0              (??LAST DAY 40% OFF???? Household long handle ...          0

Ship_Month                                                            \
Shipment_Date 2023-12-02 2023-12-03 2023-12-04 2023-12-05 2023-12-06
1119                8725       3832      16508      11916       6418
495                 1666        616       2257       1583          0
491                  547        112        214        426         49
554                  468        442        484        612        842
749                    0          0       1723        472        425
...                  ...        ...        ...        ...        ...
528                    0          0          0          0          0
527                    0          0          0          0          0
524                    0          0          0          0          0
523                    0          0          0          0          0
0                      0          0          0          0          0

Ship_Month      2023-Nov                        ...                        \
Shipment_Date 2023-11-06 2023-11-07 2023-11-08  ... 2023-11-22 2023-11-23
1119                3422      10110       7082  ...       8137       6115
495                    0          0          0  ...          5       2011
491                   51        518       1029  ...        799        128
554                  291        470        733  ...        423        389
749                  386        756        585  ...        332        264
...                  ...        ...        ...  ...        ...        ...
528                    0          0          0  ...          0          0
527                    0          0          0  ...          0          0
524                    0          0          0  ...          0          0
523                    0          0          0  ...          0          0
0                      0          0          0  ...          1          0

Ship_Month                                                            \
Shipment_Date 2023-11-24 2023-11-25 2023-11-26 2023-11-27 2023-11-28
1119               12883      10150       6630      12981      16745
495                  509       1942       1445       3447       4693
491                 2949       2296         35        547        417
554                  637        286        481        595        535
749                 1019        547          0        368        267
...                  ...        ...        ...        ...        ...
528                    0          0          0          1          0
527                    0          0          0          1          0
524                    1          0          0          0          0
523                    0          0          0          1          0
0                      0          0          0          0          0

Ship_Month                          Grand_Total
Shipment_Date 2023-11-29 2023-11-30
1119                9029      12753      257264
495                 1217       1765       39188
491                  449        567       25670
554                  341        492       16914
749                  365        288       14916
...                  ...        ...         ...
528                    0          0           1
527                    0          0           1
524                    0          0           1
523                    0          0           1
0                      0          0           1

[1120 rows x 33 columns]

In [72]:
# pd.concat([table,table.sum(level=[0,1]).assign(iten_name='result').set_index('iten_name',
#                                                                              append=True)]).sort_index(level=[0,1,2])